---
name: Auto Bump Version
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  GITHUB_TOKEN: ${{ secrets.GH_RO_TOKEN }}
  
jobs:
  bump:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci --force
      - run: npm run build --if-present
    # - run: npm test -- --watch=false --browsers=ChromeHeadless
      - run: npx semantic-release
      - run: ls -la
